import Link from "next/link";
import { asc } from "drizzle-orm";
import { Archive, Copy, ExternalLink, Plus } from "lucide-react";
import { db, getSettings } from "@/db";
import * as s from "@/db/schema";
import { listValueSets, rankings, valuesForSet } from "@/db/services";
import { addValueAction, archiveValueAction, createSetAction, importPresetAction, mergeSetsAction, updateSetAction, updateValueAction } from "../actions";
import { EmptyState, PageHeader, Panel } from "@/components/ui";

export default async function ValuesPage({ searchParams }: { searchParams: Promise<{ set?: string; filter?: string; duplicates?: string }> }) {
  const query = await searchParams; const sets = listValueSets(); const selected = sets.find((set) => set.id === query.set) ?? sets[0]; const settings = getSettings();
  const presets = db.select().from(s.presets).orderBy(asc(s.presets.name)).all(); const values = selected ? valuesForSet(selected.id, true) : []; const ratings = selected ? rankings(selected.id) : [];
  const filtered = query.filter === "sparse" ? values.filter((value) => (ratings.find((row) => row.valueId === value.id)?.comparisons ?? 0) < settings.convergence.minimumComparisons) : values;
  return <div className="page"><PageHeader title="Values" description="Manage taxonomies, source metadata, aliases, definitions, and revision history." actions={<a className="btn" href="#new-set"><Plus size={16} /> New set</a>} />
    {query.duplicates && <div className="notice notice-warning" style={{ marginBottom: 16 }}><strong>Merge duplicate review</strong><div>{query.duplicates}</div></div>}
    <div className="grid two-col"><div className="stack">
      <Panel title="Value sets">{sets.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Set</th><th>Source</th><th>Values</th><th></th></tr></thead><tbody>{sets.map((set) => <tr key={set.id}><td><Link href={`/values?set=${set.id}`}><strong>{set.name}</strong><div className="small muted">{set.description}</div></Link></td><td><span className="badge">{set.sourceType}</span></td><td>{set.valueCount}</td><td><Link className="btn btn-icon btn-sm" href={`/values?set=${set.id}`} title="Open set"><ExternalLink size={14} /></Link></td></tr>)}</tbody></table></div> : <EmptyState title="No value sets">Create one or import a preset.</EmptyState>}</Panel>
      {selected && <Panel title={`${selected.name} values`} action={<span className="badge">{filtered.filter((value) => value.active).length} active</span>}>{filtered.length ? <div className="stack">{filtered.map((value) => { const rating = ratings.find((row) => row.valueId === value.id); return <details className="panel" key={value.id} style={{ opacity: value.active ? 1 : .6 }}><summary className="panel-head"><span><strong>{value.name}</strong> <span className="badge">{value.parentCategory || "Uncategorized"}</span></span><span className="small muted">{rating?.comparisons ?? 0} comparisons · σ {rating?.sigma.toFixed(2) ?? "—"}</span></summary><div className="panel-body"><form action={updateValueAction}><input type="hidden" name="id" value={value.id} /><div className="form-grid"><div className="field"><label>Name</label><input className="input" name="name" defaultValue={value.name} required /></div><div className="field"><label>Parent category</label><input className="input" name="parentCategory" defaultValue={value.parentCategory} /></div><div className="field"><label>Current short definition</label><textarea className="textarea" name="shortDefinition" defaultValue={value.shortDefinition} /></div><div className="field"><label>Personal definition</label><textarea className="textarea" name="personalDefinition" defaultValue={value.personalDefinition} /></div><div className="field"><label>Aliases, comma separated</label><input className="input" name="aliases" defaultValue={value.aliases.join(", ")} /></div><div className="field"><label>Revision note</label><input className="input" name="changeNote" placeholder="Why did this definition change?" /></div></div><div className="form-actions"><Link className="btn" href={`/values/${value.id}`}>Evidence profile</Link><button className="btn btn-primary" type="submit">Save revision</button></div></form><form action={archiveValueAction}><input type="hidden" name="id" value={value.id} /><button className="btn btn-sm btn-danger"><Archive size={14} /> {value.active ? "Archive" : "Restore"}</button></form></div></details>; })}</div> : <EmptyState title="No matching values">Adjust the filter or add a value.</EmptyState>}</Panel>}
    </div><div className="stack">
      {selected && <><Panel title="Set details"><form action={updateSetAction}><input type="hidden" name="id" value={selected.id} /><div className="stack"><div className="field"><label>Name</label><input className="input" name="name" defaultValue={selected.name} /></div><div className="field"><label>Description</label><textarea className="textarea" name="description" defaultValue={selected.description} /></div><label className="check-row"><input type="checkbox" name="archived" /> Archive set</label><button className="btn" type="submit">Save set</button></div></form></Panel><Panel title="Add value"><form action={addValueAction}><input type="hidden" name="valueSetId" value={selected.id} /><div className="stack"><div className="field"><label>Name</label><input className="input" name="name" required /></div><div className="field"><label>Definition</label><textarea className="textarea" name="shortDefinition" /></div><div className="field"><label>Parent category</label><input className="input" name="parentCategory" /></div><button className="btn btn-primary" type="submit"><Plus size={15} /> Add value</button></div></form></Panel></>}
      <Panel title="Built-in presets"><div className="stack">{presets.map((preset) => <form className="spread" action={importPresetAction} key={preset.id}><div><strong>{preset.name}</strong><div className="small muted">{(preset.data as { values?: unknown[] }).values?.length ?? 0} values</div></div><input type="hidden" name="slug" value={preset.slug} /><button className="btn btn-sm">Import</button></form>)}</div></Panel>
      <Panel title="Create or combine"><details id="new-set"><summary>Create empty custom set</summary><form action={createSetAction} className="stack" style={{ marginTop: 12 }}><div className="field"><label>Name</label><input className="input" name="name" required /></div><div className="field"><label>Description</label><textarea className="textarea" name="description" /></div><button className="btn" type="submit">Create set</button></form></details><hr className="divider" /><details><summary>Clone or merge sets</summary><form action={mergeSetsAction} className="stack" style={{ marginTop: 12 }}><div className="field"><label>New set name</label><input className="input" name="name" required defaultValue={selected ? `${selected.name} copy` : "Merged values"} /></div>{sets.map((set) => <label className="check-row" key={set.id}><input type="checkbox" name="setIds" value={set.id} defaultChecked={set.id === selected?.id} /> {set.name}</label>)}<button className="btn" type="submit"><Copy size={14} /> Clone or merge</button></form></details></Panel>
    </div></div>
  </div>;
}
