import Link from "next/link";
import { asc, desc, eq } from "drizzle-orm";
import { Play, Pause } from "lucide-react";
import { db, getSettings } from "@/db";
import * as s from "@/db/schema";
import { listValueSets, rankings, valuesForSet } from "@/db/services";
import { EmptyState, PageHeader, Panel } from "@/components/ui";
import { ComparisonForm } from "@/components/comparison-form";
import { setSessionStatusAction, startSessionAction } from "../actions";

export default async function ComparePage({ searchParams }: { searchParams: Promise<{ session?: string }> }) {
  const query = await searchParams; const sets = listValueSets(); const contexts = db.select().from(s.contexts).where(eq(s.contexts.archived, false)).orderBy(asc(s.contexts.name)).all();
  const sessions = db.select().from(s.comparisonSessions).orderBy(desc(s.comparisonSessions.updatedAt)).all();
  const session = query.session ? sessions.find((item) => item.id === query.session) : sessions.find((item) => item.status === "active");
  if (!session) return <div className="page"><PageHeader title="Compare" description="Start a focused session. You can pause without losing the queue or notes." /><div className="grid two-col"><Panel title="New comparison session">{sets.length ? <form action={startSessionAction}><div className="form-grid"><div className="field"><label htmlFor="name">Session name</label><input className="input" id="name" name="name" required placeholder="Clarify my overall priorities" /></div><div className="field"><label htmlFor="valueSetId">Value set</label><select className="select" id="valueSetId" name="valueSetId" required>{sets.map((set) => <option key={set.id} value={set.id}>{set.name} ({set.valueCount})</option>)}</select></div><div className="field" style={{ gridColumn: "1 / -1" }}><label htmlFor="description">Purpose</label><input className="input" id="description" name="description" placeholder="What are you trying to learn?" /></div><div className="field" style={{ gridColumn: "1 / -1" }}><span className="field-label">Contexts</span><div className="row" style={{ flexWrap: "wrap" }}>{contexts.map((context) => <label className="check-row" key={context.id}><input type="checkbox" name="contextIds" value={context.id} /> {context.name}</label>)}</div></div><div className="field" style={{ gridColumn: "1 / -1" }}><label htmlFor="notes">Session notes</label><textarea className="textarea" id="notes" name="notes" /></div></div><div className="form-actions"><button className="btn btn-primary" type="submit"><Play size={16} /> Start session</button></div></form> : <EmptyState title="Create a value set first"><Link className="btn" href="/values">Open Values</Link></EmptyState>}</Panel><Panel title="Previous sessions">{sessions.length ? <div className="stack">{sessions.slice(0, 8).map((item) => <Link className="spread" key={item.id} href={`/compare?session=${item.id}`}><div><strong>{item.name}</strong><div className="small muted">{item.completedCount} comparisons</div></div><span className="badge">{item.status}</span></Link>)}</div> : <EmptyState title="No sessions yet">Completed and paused sessions appear here.</EmptyState>}</Panel></div></div>;

  if (session.status === "paused" || session.status === "completed") return <div className="page"><PageHeader title={session.name} description={session.description || "Comparison session"} /><Panel><div className="spread"><div><span className="badge">{session.status}</span><p>{session.completedCount} comparisons completed. {session.notes}</p></div><div className="row">{session.status === "paused" && <form action={setSessionStatusAction}><input type="hidden" name="id" value={session.id} /><input type="hidden" name="status" value="active" /><button className="btn btn-primary"><Play size={16} /> Resume</button></form>}<Link className="btn" href="/compare">New session</Link></div></div></Panel></div>;

  const queue = db.select().from(s.comparisonQueue).where(eq(s.comparisonQueue.sessionId, session.id)).orderBy(asc(s.comparisonQueue.position)).all(); const item = queue[0];
  if (!item) return <div className="page"><PageHeader title={session.name} description="The queue is empty." /><Panel><EmptyState title="No candidate matchup"><Link className="btn" href={`/queue?session=${session.id}`}>Regenerate the queue</Link></EmptyState></Panel></div>;
  const values = valuesForSet(session.valueSetId); const left = values.find((value) => value.id === item.leftValueId)!; const right = values.find((value) => value.id === item.rightValueId)!; const ratingRows = rankings(session.valueSetId);
  const noteRows = db.select().from(s.comparisonNotes).all(); const relevantEventIds = db.select().from(s.comparisonEvents).where(eq(s.comparisonEvents.valueSetId, session.valueSetId)).all().filter((event) => [left.id, right.id].includes(event.leftValueId) || [left.id, right.id].includes(event.rightValueId)).map((event) => event.id); const relevantNotes = relevantEventIds.length ? noteRows.filter((note) => relevantEventIds.includes(note.eventId)) : [];
  const sessionContextIds = db.select().from(s.sessionContexts).where(eq(s.sessionContexts.sessionId, session.id)).all().map((row) => row.contextId); const settings = getSettings();
  const view = (value: typeof left) => ({ id: value.id, name: value.name, definition: value.personalDefinition || value.shortDefinition, sourceDefinition: value.sourceDefinition, taxonomy: value.sourceTaxonomy, category: value.parentCategory, notes: relevantNotes.map((note) => note.text).slice(0, 2), rank: ratingRows.findIndex((row) => row.valueId === value.id) + 1, sigma: ratingRows.find((row) => row.valueId === value.id)?.sigma });
  return <div className="page"><PageHeader title={session.name} description={`${session.completedCount} completed · ${queue.length} queued · ${item.reason}`} actions={<form action={setSessionStatusAction}><input type="hidden" name="id" value={session.id} /><input type="hidden" name="status" value="paused" /><button className="btn"><Pause size={16} /> Pause</button></form>} /><ComparisonForm sessionId={session.id} valueSetId={session.valueSetId} left={view(left)} right={view(right)} contexts={contexts} defaultContextIds={sessionContextIds} selectionReason={item.reason} showRatings={settings.display.showRatingsDuringComparison} /></div>;
}
