import Link from "next/link";
import { asc, eq, inArray } from "drizzle-orm";
import { Download, Info } from "lucide-react";
import { db, getSettings } from "@/db";
import * as s from "@/db/schema";
import { listValueSets, rankings, ratingEventsForSet, valuesForSet } from "@/db/services";
import { estimateRanks } from "@/domain/statistics";
import { conservativeScore, TrueSkillRatingSystem } from "@/domain/rating";
import { convergenceDiagnostics } from "@/domain/convergence";
import { EmptyState, PageHeader, Panel } from "@/components/ui";
import { ManualTiers } from "@/components/manual-tiers";

const views = ["exact", "tiers", "uncertainty", "matrix", "probabilities", "categories", "contexts", "timeline", "diagnostics", "manual"];

export default async function RankingsPage({ searchParams }: { searchParams: Promise<{ set?: string; context?: string; evidence?: string; view?: string; snapshot?: string }> }) {
  const query = await searchParams; const sets = listValueSets(); const selected = sets.find((set) => set.id === query.set) ?? sets[0]; const view = views.includes(query.view ?? "") ? query.view! : "exact"; const contexts = db.select().from(s.contexts).where(eq(s.contexts.archived, false)).orderBy(asc(s.contexts.name)).all();
  if (!selected) return <div className="page"><PageHeader title="Rankings" description="Posterior rankings, stable tiers, uncertainty, and context-specific differences." /><Panel><EmptyState title="No value set"><Link className="btn" href="/values">Create or import values</Link></EmptyState></Panel></div>;
  const scopeKey = query.context ? `${query.evidence === "filtered" ? "context" : "combined"}:${query.context}` : "global"; const rows = rankings(selected.id, scopeKey); const settings = getSettings(); const rankEstimates = estimateRanks(new Map(rows.map((row) => [row.valueId, row])), settings.convergence.topK, 2000, 1729); const values = valuesForSet(selected.id); const events = ratingEventsForSet(selected.id); const system = new TrueSkillRatingSystem(settings.rating);
  const snapshots = db.select().from(s.ratingSnapshots).where(eq(s.ratingSnapshots.valueSetId, selected.id)).orderBy(asc(s.ratingSnapshots.createdAt)).all(); const snapshotEntries = snapshots.length ? db.select().from(s.ratingSnapshotEntries).where(inArray(s.ratingSnapshotEntries.snapshotId, snapshots.map((snapshot) => snapshot.id))).all() : [];
  const recentRankings = snapshots.slice(-settings.convergence.stabilityWindow).map((snapshot) => snapshotEntries.filter((entry) => entry.snapshotId === snapshot.id).sort((a, b) => a.rank - b.rank).map((entry) => entry.valueId));
  const diagnostics = convergenceDiagnostics({ values: rows.map((row) => ({ id: row.valueId, name: row.value.name, aliases: row.value.aliases, parentCategory: row.value.parentCategory, rating: row })), recentRankings, config: settings.convergence, suspectedContradictions: db.select().from(s.tensions).where(eq(s.tensions.status, "suggested")).all().length });
  const tiers: typeof rows[] = []; for (const row of rows) { const previous = tiers.at(-1)?.at(-1); if (!previous || Math.abs(previous.mu - row.mu) > Math.sqrt(previous.sigma ** 2 + row.sigma ** 2)) tiers.push([row]); else tiers.at(-1)!.push(row); }
  const manualTierRows = db.select().from(s.manualTiers).where(eq(s.manualTiers.valueSetId, selected.id)).orderBy(asc(s.manualTiers.position)).all(); const manualIds = manualTierRows.map((tier) => tier.id); const manualLinks = manualIds.length ? db.select().from(s.manualTierValues).where(inArray(s.manualTierValues.tierId, manualIds)).all() : [];
  const href = (nextView: string) => `/rankings?set=${selected.id}${query.context ? `&context=${query.context}&evidence=${query.evidence ?? "combined"}` : ""}&view=${nextView}`;
  return <div className="page"><PageHeader title="Rankings" description="Uncertainty is retained throughout. Overlapping posterior distributions are grouped rather than forced into a certain total order." actions={<a className="btn" href={`/api/export/csv?file=ratings`}><Download size={16} /> Export ratings</a>} />
    <Panel><form className="form-grid" action="/rankings"><div className="field"><label>Value set</label><select className="select" name="set" defaultValue={selected.id}>{sets.map((set) => <option value={set.id} key={set.id}>{set.name}</option>)}</select></div><div className="field"><label>Context</label><select className="select" name="context" defaultValue={query.context ?? ""}><option value="">Global ranking</option>{contexts.map((context) => <option value={context.id} key={context.id}>{context.name}</option>)}</select></div><div className="field"><label>Context evidence</label><select className="select" name="evidence" defaultValue={query.evidence ?? "combined"}><option value="combined">Global + selected context</option><option value="filtered">Selected context only</option></select></div><input type="hidden" name="view" value={view} /><div className="form-actions"><button className="btn" type="submit">Apply filters</button></div></form></Panel>
    <nav className="tabs" style={{ marginTop: 16 }} aria-label="Ranking views">{views.map((item) => <Link key={item} className={`tab ${item === view ? "tab-active" : ""}`} href={href(item)}>{item[0]!.toUpperCase() + item.slice(1)}</Link>)}</nav>
    <section style={{ marginTop: 16 }}>
      {view === "exact" && <Panel title="Posterior ordering" action={<span className="badge">{scopeKey.replace(":", " · ")}</span>}>{rows.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Rank</th><th>Value</th><th>Mean</th><th>Uncertainty</th><th>Conservative</th><th>Rank interval</th><th>Top-{settings.convergence.topK}</th><th>Evidence</th></tr></thead><tbody>{rows.map((row, index) => { const estimate = rankEstimates.get(row.valueId)!; return <tr key={row.valueId}><td><span className="rank-number">{index + 1}</span></td><td><Link href={`/values/${row.valueId}`}><strong>{row.value.name}</strong><div className="small muted">{row.value.parentCategory}</div></Link></td><td className="mono">{row.mu.toFixed(2)}</td><td><div className="row"><div className="uncertainty-track"><span style={{ width: `${Math.min(100, row.sigma / settings.rating.sigma * 100)}%` }} /></div><span className="mono">{row.sigma.toFixed(2)}</span></div></td><td className="mono">{conservativeScore(row, settings.rating.conservativeK).toFixed(2)}</td><td>{estimate.low}-{estimate.high}</td><td>{Math.round(estimate.topKProbability * 100)}%</td><td>{row.comparisons}</td></tr>; })}</tbody></table></div> : <EmptyState title="No ratings">Add active values to this set.</EmptyState>}</Panel>}
      {view === "tiers" && <div className="stack"><div className="notice"><strong>Inferred stable tiers</strong><div className="small">Adjacent values share a tier when their posterior distributions overlap by the configured separation rule.</div></div>{tiers.map((tier, index) => <Panel key={index} title={`Tier ${String.fromCharCode(65 + index)} · ${tier.length} value${tier.length === 1 ? "" : "s"}`}><div className="row" style={{ flexWrap: "wrap" }}>{tier.map((row) => <span className="badge badge-accent" key={row.valueId}>{row.value.name} · {row.mu.toFixed(1)} ± {row.sigma.toFixed(1)}</span>)}</div></Panel>)}</div>}
      {view === "uncertainty" && <Panel title="Posterior uncertainty plot"><div className="stack">{rows.map((row) => { const low = row.mu - 2 * row.sigma; const high = row.mu + 2 * row.sigma; const min = Math.min(...rows.map((item) => item.mu - 2 * item.sigma)); const max = Math.max(...rows.map((item) => item.mu + 2 * item.sigma)); const pct = (value: number) => (value - min) / Math.max(1, max - min) * 100; return <div key={row.valueId}><div className="spread small"><strong>{row.value.name}</strong><span className="mono">95% interval {low.toFixed(1)}–{high.toFixed(1)}</span></div><div className="plot"><span className="plot-line" style={{ left: `${pct(low)}%`, width: `${pct(high) - pct(low)}%` }} /><span className="plot-dot" style={{ left: `${pct(row.mu)}%` }} /></div></div>; })}</div></Panel>}
      {view === "matrix" && <Panel title="Comparison matrix"><div className="table-wrap"><table className="table"><thead><tr><th>Value</th>{values.map((value) => <th key={value.id}>{value.name.slice(0, 12)}</th>)}</tr></thead><tbody>{values.map((a) => <tr key={a.id}><th>{a.name}</th>{values.map((b) => { const paired = events.filter((event) => [event.leftValueId, event.rightValueId].includes(a.id) && [event.leftValueId, event.rightValueId].includes(b.id)); const wins = paired.filter((event) => (event.result === "left" ? event.leftValueId : event.result === "right" ? event.rightValueId : "") === a.id).length; return <td key={b.id}>{a.id === b.id ? "—" : paired.length ? `${wins}/${paired.length}` : "·"}</td>; })}</tr>)}</tbody></table></div></Panel>}
      {view === "probabilities" && <Panel title="Pairwise win probabilities"><div className="table-wrap"><table className="table"><thead><tr><th>Value</th>{rows.map((row) => <th key={row.valueId}>{row.value.name.slice(0, 12)}</th>)}</tr></thead><tbody>{rows.map((a) => <tr key={a.valueId}><th>{a.value.name}</th>{rows.map((b) => <td key={b.valueId}>{a.valueId === b.valueId ? "—" : `${Math.round(system.winProbability(a, b) * 100)}%`}</td>)}</tr>)}</tbody></table></div></Panel>}
      {view === "categories" && <Panel title="Category summary"><div className="table-wrap"><table className="table"><thead><tr><th>Category</th><th>Values</th><th>Average mean</th><th>Average uncertainty</th></tr></thead><tbody>{[...new Set(rows.map((row) => row.value.parentCategory || "Uncategorized"))].map((category) => { const categoryRows = rows.filter((row) => (row.value.parentCategory || "Uncategorized") === category); return <tr key={category}><td><strong>{category}</strong></td><td>{categoryRows.length}</td><td>{(categoryRows.reduce((sum, row) => sum + row.mu, 0) / categoryRows.length).toFixed(2)}</td><td>{(categoryRows.reduce((sum, row) => sum + row.sigma, 0) / categoryRows.length).toFixed(2)}</td></tr>; })}</tbody></table></div></Panel>}
      {view === "contexts" && <Panel title="Context comparison"><div className="table-wrap"><table className="table"><thead><tr><th>Value</th><th>Global</th>{contexts.map((context) => <th key={context.id}>{context.name}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.valueId}><td><strong>{row.value.name}</strong></td><td>{rankings(selected.id).findIndex((item) => item.valueId === row.valueId) + 1}</td>{contexts.map((context) => <td key={context.id}>{rankings(selected.id, `context:${context.id}`).findIndex((item) => item.valueId === row.valueId) + 1}</td>)}</tr>)}</tbody></table></div></Panel>}
      {view === "timeline" && <Panel title="Ranking changes over time">{snapshots.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Timestamp</th><th>Reason</th><th>Top three</th><th>Evidence event</th></tr></thead><tbody>{snapshots.map((snapshot) => <tr key={snapshot.id}><td>{snapshot.createdAt.toLocaleString()}</td><td>{snapshot.reason}</td><td>{snapshotEntries.filter((entry) => entry.snapshotId === snapshot.id).sort((a, b) => a.rank - b.rank).slice(0, 3).map((entry) => values.find((value) => value.id === entry.valueId)?.name).join(" · ")}</td><td className="mono">{snapshot.eventId?.slice(0, 8) ?? "—"}</td></tr>)}</tbody></table></div> : <EmptyState title="No snapshots">Snapshots appear after comparisons and session boundaries.</EmptyState>}</Panel>}
      {view === "diagnostics" && <div className="grid metrics"><div className="panel metric"><div className="metric-label">Average uncertainty</div><div className="metric-value">{diagnostics.averageUncertainty.toFixed(2)}</div></div><div className="panel metric"><div className="metric-label">Max uncertainty</div><div className="metric-value">{diagnostics.maximumUncertainty.toFixed(2)}</div></div><div className="panel metric"><div className="metric-label">Top-k stability</div><div className="metric-value">{Math.round(diagnostics.topKStability * 100)}%</div></div><div className="panel metric"><div className="metric-label">Rank correlation</div><div className="metric-value">{diagnostics.rankCorrelation.toFixed(2)}</div></div><div className="panel metric"><div className="metric-label">Adjacent order floor</div><div className="metric-value">{Math.round(diagnostics.minimumAdjacentOrderProbability * 100)}%</div></div><div className="panel metric"><div className="metric-label">Sparse values</div><div className="metric-value">{diagnostics.insufficientValues}</div></div><div className="panel metric"><div className="metric-label">Near-ties</div><div className="metric-value">{diagnostics.unresolvedNearTies}</div></div><div className="panel metric"><div className="metric-label">Category coverage</div><div className="metric-value">{Math.round(diagnostics.categoryCoverage * 100)}%</div></div><Panel title="Interpretation" className=""><div className="row"><Info size={17} /><strong>{diagnostics.state.replaceAll("-", " ")}</strong></div><p>{diagnostics.explanation}</p></Panel></div>}
      {view === "manual" && <div className="stack"><div className="notice notice-warning"><strong>Manual organization is not an inferred result</strong><div className="small">Drag values to express a personal grouping. Statistical rankings and tension detection keep this separate and may flag large disagreement.</div></div><ManualTiers valueSetId={selected.id} values={values.map((value) => ({ id: value.id, name: value.name }))} initial={manualTierRows.map((tier) => ({ name: tier.name, valueIds: manualLinks.filter((link) => link.tierId === tier.id).sort((a, b) => a.position - b.position).map((link) => link.valueId) }))} /></div>}
    </section>
  </div>;
}
