import Link from "next/link";
import { asc, desc, eq } from "drizzle-orm";
import { ArrowDown, ArrowUp, RefreshCw, Scale } from "lucide-react";
import { db } from "@/db";
import * as s from "@/db/schema";
import { valuesForSet } from "@/db/services";
import { EmptyState, PageHeader, Panel } from "@/components/ui";
import { addManualQueueAction, moveQueueItemAction, regenerateQueueAction } from "../actions";

export default async function QueuePage({ searchParams }: { searchParams: Promise<{ session?: string }> }) {
  const query = await searchParams; const sessions = db.select().from(s.comparisonSessions).orderBy(desc(s.comparisonSessions.updatedAt)).all();
  const session = sessions.find((item) => item.id === query.session) ?? sessions.find((item) => item.status === "active") ?? sessions[0];
  if (!session) return <div className="page"><PageHeader title="Comparison queue" description="The next required ordering comparison and any manual pairs." /><Panel><EmptyState title="No sessions"><Link className="btn btn-primary" href="/compare">Start a session</Link></EmptyState></Panel></div>;
  const values = valuesForSet(session.valueSetId); const queue = db.select().from(s.comparisonQueue).where(eq(s.comparisonQueue.sessionId, session.id)).orderBy(asc(s.comparisonQueue.position)).all();
  return <div className="page"><PageHeader title="Comparison queue" description={`${session.name} · one finite ordering comparison at a time.`} actions={<div className="row"><form action={regenerateQueueAction}><input type="hidden" name="sessionId" value={session.id} /><button className="btn"><RefreshCw size={16} /> Refresh next</button></form><Link className="btn btn-primary" href={`/compare?session=${session.id}`}><Scale size={16} /> Compare next</Link></div>} />
    <div className="grid two-col"><Panel title="Next required comparison">{queue.length ? <div className="table-wrap"><table className="table"><thead><tr><th>#</th><th>Pair</th><th>Selection reason</th><th>Order</th></tr></thead><tbody>{queue.map((item, index) => { const left = values.find((value) => value.id === item.leftValueId); const right = values.find((value) => value.id === item.rightValueId); return <tr key={item.id}><td>{index + 1}</td><td><strong>{left?.name}</strong><span className="muted"> vs </span><strong>{right?.name}</strong></td><td><span className="badge badge-accent">{item.reason}</span></td><td><div className="row"><form action={moveQueueItemAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="up" /><button className="btn btn-icon btn-sm" disabled={index === 0} title="Move up"><ArrowUp size={14} /></button></form><form action={moveQueueItemAction}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="direction" value="down" /><button className="btn btn-icon btn-sm" disabled={index === queue.length - 1} title="Move down"><ArrowDown size={14} /></button></form></div></td></tr>; })}</tbody></table></div> : <EmptyState title="Queue is empty">The ordering is complete, or add a manual pair.</EmptyState>}</Panel>
      <Panel title="Manual comparison"><form action={addManualQueueAction}><input type="hidden" name="sessionId" value={session.id} /><div className="stack"><div className="field"><label htmlFor="leftValueId">First value</label><select className="select" id="leftValueId" name="leftValueId">{values.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></div><div className="field"><label htmlFor="rightValueId">Second value</label><select className="select" id="rightValueId" name="rightValueId" defaultValue={values[1]?.id}>{values.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></div><button className="btn" type="submit">Add to queue</button></div></form><hr className="divider" /><div className="notice small">Manual pairs are labeled and remain in the same immutable event history. They update ratings identically to scheduled pairs.</div></Panel>
    </div>
  </div>;
}
